[2024-06-26T08:06:59.508+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: update_allogistic.run_notebook manual__2024-06-26T07:59:48.548247+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
